### ISSUE TITLE
Adding RP2040 and nRF8240 board support

### ISSUE THREAD

**Issue by djecken** [adafruit/Adafruit_CircuitPython_MatrixPortal#74]
Hiya @makermelissa Working on adding board support for RP2040 and nRF52840 feathers.

Updating the **matrix.py** page. I updated the pins for the nRF5240 and added pins for RP2040.

Starts around **line 101**

```py        elif "Feather" in os.uname().machine:
            # Feather Style Board
            if "nRF52840" in os.uname().sysname:
                # nrf52840 Style Feather
                addr_pins = [board.D10, board.D5, board.D13]
                if panel_height > 16:
                    addr_pins.append(board.D9)
                rgb_pins = [board.D6, board.A5, board.A1, board.A0, board.A4, board.D11]
                clock_pin = board.D12
                latch_pin = board.RX
                oe_pin = board.TX
            if "rp2040" in os.uname().sysname:
                # rp2040 Style Feather
                addr_pins = [board.D25, board.D24, board.A3]
                if panel_height > 16:
                    addr_pins.append(board.A2)
                rgb_pins = [board.D6, board.D5, board.D9, board.D11, board.D10, board.D12]
                clock_pin = board.D13
                latch_pin = board.D0
                oe_pin = board.D1
            else:
                addr_pins = [board.A5, board.A4, board.A3]
                if panel_height > 16:
                    addr_pins.append(board.A2)
                rgb_pins = [
                    board.D6,
                    board.D5,
                    board.D9,
                    board.D11,
                    board.D10,
                    board.D12,
                ]
                clock_pin = board.D13
            latch_pin = board.D0
            oe_pin = board.D1
```
With the modified matrix.py I got the RP2040 working fine but the nRF52840 throws an error in the REPL

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 19, in <module>
  File "/lib/adafruit_matrixportal/matrix.py", line 134, in __init__
AttributeError: 'module' object has no attribute 'D0'
```

**Comment by ladyada** [comment]
@djecken pleae edit so the code chunk is readable

**Comment by djecken** [comment]
@ladyada The code formatting looks fine when I go to edit it but then the line breaks are striped when I click Update. Sorry!

**Comment by djecken** [comment]
updated code formatting. thanks

**Comment by ladyada** [comment]
![image](https://user-images.githubusercontent.com/1214161/114422901-ad468380-9b84-11eb-939d-4a6344d4976f.png)

should be elif

**Comment by makermelissa** [comment]
I think you'll want to indent the bottom two lines as well:
```
                latch_pin = board.D0
                oe_pin = board.D1
```

**Comment by ladyada** [comment]
@djecken did this get resolved? if so please submit a PR?

**Comment by djecken** [comment]
@ladyada @makermelissa Thanks, I tried the edits above and still getting similar error. Here's a bigger chunck to check out

```py
        elif "Feather" in os.uname().machine:
            # Feather Style Board
            if "nRF52840" in os.uname().sysname:
                # nrf52840 Style Feather
                addr_pins = [board.D10, board.D5, board.D13]
                if panel_height > 16:
                    addr_pins.append(board.D9)
                rgb_pins = [board.D6, board.A5, board.A1, board.A0, board.A4, board.D11]
                clock_pin = board.D12
                latch_pin = board.RX
                oe_pin = board.TX
            elif "rp2040" in os.uname().sysname:
                # rp2040 Style Feather
                addr_pins = [board.D25, board.D24, board.A3]
                if panel_height > 16:
                    addr_pins.append(board.A2)
                rgb_pins = [board.D6, board.D5, board.D9, board.D11, board.D10, board.D12]
                clock_pin = board.D13
                latch_pin = board.D0
                oe_pin = board.D1
            else:
                addr_pins = [board.A5, board.A4, board.A3]
                if panel_height > 16:
                    addr_pins.append(board.A2)
                rgb_pins = [
                    board.D6,
                    board.D5,
                    board.D9,
                    board.D11,
                    board.D10,
                    board.D12,
                ]
                clock_pin = board.D13
                latch_pin = board.D0
                oe_pin = board.D1
        else:
            # Metro/Grand Central Style Board
            if alt_addr_pins is None and height <= 16:
                raise RuntimeError(
                    "Pin A2 unavailable in this mode. Please specify alt_addr_pins."
                )
            addr_pins = [board.A0, board.A1, board.A2, board.A3]
            rgb_pins = [board.D2, board.D3, board.D4, board.D5, board.D6, board.D7]
            clock_pin = board.A4
            latch_pin = board.D10
            oe_pin = board.D9

```

Here's the error from REPL:

```py
Traceback (most recent call last):
  File "code.py", line 19, in <module>
  File "/lib/adafruit_matrixportal/matrix.py", line 134, in __init__
AttributeError: 'module' object has no attribute 'D0'
```

**Comment by djecken** [comment]
The error is only showing up for the nRF52840 board. This works fine with the M4 and RP2040 feathers.

**Comment by makermelissa** [comment]
I think the original code was:
```
if "nrf52" in os.uname().sysname:
```
I think the reason for that was because the full "nRF52840" was not be appearing in sysname.

**Comment by djecken** [comment]
@makermelissa That was it! Thank you 😸
