### ISSUE TITLE
Compatibility with 96x48 Waveshare Matrix

### ISSUE THREAD

**Issue by Swiftnesses** [adafruit/Adafruit_CircuitPython_MatrixPortal#95]
Good day,

I'm trying to use this with this matrix: https://www.waveshare.com/wiki/RGB-Matrix-P2.5-96x48-F

I can initialise with `width=96`, but using `height=48` leads to error:

```
Traceback (most recent call last):
  File "code.py", line 35, in <module>
  File "adafruit_matrixportal/matrixportal.py", line 96, in __init__
  File "adafruit_matrixportal/graphics.py", line 67, in __init__
  File "adafruit_matrixportal/matrix.py", line 209, in __init__
RuntimeError: Failed to initialize RGB Matrix
```

Here is my test code:

```
matrixportal = MatrixPortal(
    url=DATA_SOURCE,
    json_path=DATA_LOCATION,
    status_neopixel=board.NEOPIXEL,
    width=96, 
    height=48
)
```

When the height of the display is set to 32/64, it works, but doesn't display properly.

**Comment by makermelissa** [comment]
Try 64 for the height. Generally matrix panel heights are a power of 2 (16, 32, 64, 128, etc.). They may just be showing 48 pixels of the 64.
